#lang scheme
(display "Hello World")
(newline)
(display "Enter 2 Numbers")
(newline)
(define a (read))
(define b (read))
(display a)
(display "+")
(display b)
(display "=")
(display (+ a b))
(newline)
